apiVersion: v1
kind: Service
metadata:
  name: ecommerce-backend-service-v2
spec:
  selector:
    app: ecommerce-backend-v2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
