apiVersion: v1
kind: Service
metadata:
  name: gitops-react-java-app-backend-lb
  namespace: gitops-apps
spec:
  selector:
    app: gitops-react-java-app-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
